#! /bin/sh
### BEGIN INIT INFO
# Provides: hornetq
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: HornetQ
# Description: This file starts and stops HornetQ server
# 
### END INIT INFO

HORNETQ_HOME=/opt/hornetq-2.4.1.Final
export HORNETQ_HOME

case "$1" in
 start)
   $HORNETQ_HOME/bin/run.sh &
   ;;
 stop)
   $HORNETQ_HOME/bin/stop.sh
   sleep 10
   ;;
 restart)
   $HORNETQ_HOME/bin/stop.sh
   sleep 20
   $HORNETQ_HOME/bin/run.sh &
   ;;
 *)
   echo "Usage: hornetq {start|stop|restart}" >&2
   exit 3
   ;;
esac
